---

- hosts: localhost
  become: true
  vars_files:
    - vars.yml


  tasks:

  - name: Stop Logstash
    service: name=logstash state=stopped

  - name: Add X-Pack to Logstash
    command: ./bin/logstash-plugin install file:///opt/x-pack.zip
    args:
      chdir: /usr/share/logstash/

  - name: Add the Logstash input configuration for Beats
    template: src=templates/beats-input.conf dest=/etc/logstash/conf.d/00-beats-input.conf

  - name: Add the Logstash filter
    template: src=templates/postgresql-filter.conf dest=/etc/logstash/conf.d/10-postgresql-filter.conf

  - name: Add the Logstash output configuration to Elasticsearch
    template: src=templates/elasticsearch-output.conf dest=/etc/logstash/conf.d/20-elasticsearch-output.conf

  - name: Start Logstash
    service: name=logstash state=started
